version: '2'
services:
  webapp:
    env_file:
      - ./.env.test
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "9876"
    depends_on:
      - neo4j
      - redis
    links:
      - neo4j
      - redis
    volumes:
      - /usr/src/app/coverage
    command: npm run test && npm run server:coverage && npm run server:coverage:func && npm run coverage:combine

  redis:
    image: redis:3.2.3
    expose:
      - "6379"
  neo4j:
    image: neo4j:3.0.4
    expose:
      - "7474"
      - "7687"
    environment:
      NEO4J_AUTH: none
