export const GET_RECENT_POSTS = 'GET_RECENT_POSTS';
export const GET_RECENT_POSTS_SUCCESS = 'GET_RECENT_POSTS_SUCCESS';
export const GET_RECENT_POSTS_FAILURE = 'GET_RECENT_POSTS_FAILURE';
export const RESET_GET_RECENT_POSTS = 'RESET_GET_RECENT_POSTS';
