export const GET_USER_POSTS = 'GET_USER_POSTS';
export const GET_USER_POSTS_SUCCESS = 'GET_USER_POSTS_SUCCESS';
export const GET_USER_POSTS_FAILURE = 'GET_USER_POSTS_FAILURE';
export const RESET_GET_USER_POSTS = 'RESET_GET_USER_POSTS';

export const REMOVE_POST = 'REMOVE_POST';
export const REMOVE_POST_SUCCESS = 'REMOVE_POST_SUCCESS';
export const REMOVE_POST_FAILURE = 'REMOVE_POST_FAILURE';
export const RESET_REMOVE_POST = 'RESET_REMOVE_POST';
